#노무현 대통령 취임식 연설문 Word Cloud
install.packages('KoNLP')
install.packages('RColorBrewer')
install.packages('wordcloud')
library(KoNLP)
library(RColorBrewer)
library(wordcloud)
useSejongDic()
myText<-readLines('text.txt')
head(myText)
termNoun<-sapply(myText,extractNoun,USE.NAMES = F)
head(termNoun,10)
dics<-c('sejong','woorimalsam')
user_d<-data.frame(term='김대중',tag='ncn')
buildDictionary(ext_dic = dics,user_dic = user_d)
term2<-unlist(termNoun)
term2
head(term2,20)
term3<-gsub('오늘','',term2)
term3<-gsub('여러분','',term3)
term3<-gsub('하기','',term3)
head(term3,20)
term4<-Filter(function(x){nchar(x)>=2}, term3)
head(term4,20)
termcount<-table(term4)
head(termcount)
head(sort(termcount,decreasing=T),10)
mypal<-brewer.pal(8,'Dark2')
wordcloud(names(termcount), freq=termcount,scale=c(6,0,3),
          min.freq = 3,random.order = F,rot.per = 0.1,colors=mypal)
